name: Tafari Johnson
description: "... I write code"
meta_description: "Tafari Johnson - Software developer"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
permalink: "/:title"
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog url'
author:         'Tafari Johnson'

# custom stuff
date_format: "%B %d, %Y"
gravatar: "//gravatar.com/avatar/7dd92275921ceb134aa21d789900b499.png"